requires 'Algorithm::Diff', '== 1.1903';
requires 'WWW::RobotRules', '== 5.832';
requires 'Bundle::LWP', '== 5.835';
requires 'CGI::Session', '== 4.48';
requires 'Digest::MD5', '== 2.55';
requires 'File::Listing';
requires 'HTML::Template', '== 2.97';
requires 'Image::Info', '== 1.42';
requires 'Regexp::Assemble', '== 0.38';
requires 'TeX::Hyphen', '== 1.18';
requires 'Jcode', '== 2.07';
requires 'DBI', '== 1.643';
