#
# exec command: >
#   docker-compose -f docker-compose-heroku.yml --env-file .env.local up -d --build
#   docker exec -it <container name> sh
#
version: "3.9"
services:
  wiki:
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/heroku/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - webappvolume:/opt/fswiki
  db:
    image: postgres:13.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: test
      POSTGRES_PASSWORD: admin

volumes:
  webappvolume: {}
