# fly.toml app configuration file generated for fswiki on 2025-07-20T17:04:48+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fswiki'
primary_region = 'nrt'

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  auto_start_machines = true
  auto_stop_machines = 'stop'
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[build]
  dockerfile = "docker/debian/Dockerfile"

[env]
  DB_DRIVER = "mysql"
