version: '3.8'

services:
  # MySQL 8 サーバー
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: very_strong_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "--protocol=tcp", "-h", "localhost", "-u", "root", "-pvery_strong_password", "-e", "SELECT 1"]
      timeout: 60s
      retries: 30

  # Perlを実行するDebian Bookworm環境
  app:
    build: .
    # 環境変数をPerlスクリプトに渡す
    environment:
      DB_HOST: db
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASS: testpass

volumes:
  mysql-data:
