---
#
# nginxインストール
#
- name: Install nginx
  become: yes
  ansible.builtin.package:
    name: nginx
    state: latest

- name: Create cache directory
  become: yes
  file:
    dest: /var/cache/nginx/cache
    state: directory
    owner: www-data
    group: www-data

#- name: Write the original nginx config file
#  action: template src=./myapp.j2 dest=/etc/nginx/conf.d/myapp.conf

- name: Reload systemctl unit file
  systemd:
    daemon_reload: yes
  become: true

- name: Enable systemctl unit file
  systemd:
    name: nginx.service
    enabled: yes
  become: true

- name: Start systemctl unit file
  systemd:
    name: nginx.service
    state: restarted
  become: true
