---
#
# fswikiインストール前の準備など
#
- name: Install required packages
  ansible.builtin.package:
    name: "{{ packages }}"

- name: Install libssl-dev
  ansible.builtin.package:
    name: libssl-dev
  when: ansible_facts['os_family'] == 'Debian'

- name: Install openssl-devel
  ansible.builtin.package:
    name:
      - openssl
      - openssl-devel
  when: ansible_facts['os_family'] == 'RedHat'

- name: Update cerrificate of python3
  shell: pip3 install --upgrade certifi

- name: Add groups.
  group:
    name: "{{ item.name }}"
    state: "{{ (item.disabled is undefined or not item.disabled|bool)|ternary('present', 'absent') }}"
  with_items: "{{ groups_to_add }}"

- name: Add users
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    state: "{{ (item.disabled is undefined or not item.disabled|bool)|ternary('present', 'absent') }}"
    shell: /bin/bash
  with_items: "{{ users_to_add }}"

- name: Set .bash_profile
  copy:
    src: files/.bash_profile
    dest: "/home/{{ item.name }}/"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ users_to_add }}"

- name: Allow wheel group to have pliviledge of sudo without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

