- name: Install common package and create users/groups
  hosts: all
  gather_facts: true
  roles:
    - role: fswiki_common

- name: Install perlbrew for wiki server
  hosts: wiki
  gather_facts: true
  roles:
    - role: tobybro.perlbrew
      perlbrew_user: fswiki
      perl_version: perl-5.30.2
      switch_to_new_perl: false

- name: Install freestylewiki into wiki server
  hosts: wiki
  remote_user: fswiki
  roles:
    - role: fswiki_webserver
    - role: fswiki
